# obn_config.py
import numpy as np

CHNL_NUM = 4
SAMP_BUF_NUM = 1023
SAMPLE_RATE = 1000
DT_US = 1000
PACKET_DURATION_US = SAMP_BUF_NUM * DT_US
HEADER_STRUCT = "<6BHI"
HEADER_SIZE = 12
DATA_DTYPE = np.dtype("<i4")
TIMESTAMP_ALIGN = 0
YEAR_IS_OFFSET = True
H5_CHUNK_SHAPE = (16, CHNL_NUM, SAMP_BUF_NUM)
H5_COMPRESSION = "lzf"
H5_SHUFFLE = True
CHANNEL_NAMES = ["X", "Y", "Z", "H"]
GAP_POLICY = "error"
PACKET_SIZE = 16380
